### ISSUE TITLE
Crash on buying Sulfur in Greedier DD

### ISSUE THREAD

**Issue by MuuusSTMP** [aymericingargiola/repentance-run-tracker#15]
Bought Sulfur on Womb's DD in Greedier Mode as Cain, had Potato Peeler as active item when buying Sulfur.

[repentance_run_tracker_error_dump-12-4-21-111515am.zip](https://github.com/aymericingargiola/repentance-run-tracker/files/7653742/repentance_run_tracker_error_dump-12-4-21-111515am.zip)

**Comment by aymericingargiola** [comment]
Thanks for the report, it will be fixed next release !

https://github.com/aymericingargiola/repentance-run-tracker/commit/94268ec3653c9b00d4461d7cecc6c838b80b9de7
