### ISSUE TITLE
Game came back to main menu

### ISSUE THREAD

**Issue by MuuusSTMP** [aymericingargiola/repentance-run-tracker#19]
Kind of weird bug here. I entered a normal room of Downpoor I during Isaac's Awakening challenge, I lost focus on the game (playing with controller), came back to main menu while the app crashed.
[repentance_run_tracker_error_dump-12-05-21-091020PM.zip](https://github.com/aymericingargiola/repentance-run-tracker/files/7656747/repentance_run_tracker_error_dump-12-05-21-091020PM.zip)

**Comment by aymericingargiola** [comment]
Thanks, i made a fix for next release to check if last floor is undefined or not, but i'm not sure why you had this issue
