### ISSUE TITLE
Crash whil changing stage as J&E

### ISSUE THREAD

**Issue by MuuusSTMP** [aymericingargiola/repentance-run-tracker#20]
Crash when going from B1 to B2.
[repentance_run_tracker_error_dump-12-05-21-103739PM.zip](https://github.com/aymericingargiola/repentance-run-tracker/files/7656879/repentance_run_tracker_error_dump-12-05-21-103739PM.zip)

**Comment by aymericingargiola** [comment]
I think it's fixed from last hotfix, let me know if there is other issues like this !
