### ISSUE TITLE
More accurate runs filter

### ISSUE THREAD

**Issue by BensDream** [aymericingargiola/repentance-run-tracker#30]
At the moment, I keep a spreadsheet of how many times I've managed to beat the game, as well as my best streak and the seed of each run in that streak. I do this on a per-character basis, logged in a spreadsheet here:

http://docs.google.com/spreadsheets/d/1zUua36ByZNQumAzRhoEenbPoMlQ5ZH9C0hTrgeDBRvw/edit?usp=sharing

So my breakdown is:
1. Total final boss kills on each character
2. Best streak on each character (including seed)

In my spreadsheet, I also log these stats for each difficulty.

Personally, it would be really useful if the mod tracked the things I listed above!

My understanding is that Isaac doesn't put difficulty in logs, so it would be hard to implement in the mod - maybe there could be an option in the app to select a difficulty once a run has been finished?

**Comment by aymericingargiola** [comment]
Thanks for oppening the feature, i'm checking what can i do !

So, with the mod it's maybe possible to know the difficulty ! In fact, without the mod it's impossible, this is why i'v done a mod next to this app, i need more informations that the logs doesn't give. The mod add few more lines to the logs and that's it !

I know that some people don't like to play with mods so the app try to be very accurate without mods but sometimes it's not possible (like health, and player stats, or game difficulty as you ask).

So from your feature request there are few things : 

- Record each final boss killed on each character whatever the seed if i understand well
- Seed filtered runs by characters
- Extra : make a difference between Hard runs and Normal runs from streaks

It's a pretty huge feature and i'll maybe need multiple updates and tests to complete everything, also i should handle people that dosen't play with mods

**Comment by BensDream** [comment]
If it's something you'd be interested in adding it would be a big help!

I think the main thing I'm looking to do is track my highest win streaks per character, and the seeds of each run in that streak.

**Comment by aymericingargiola** [comment]
So i think, first, i should add a special filter with the characters in there current winstreak it could help you, the seed filter can be done in this search text filter, you can add the seed (this field check the character name, seed number or custom run name if you added a name to your run from the app) : 
![image](https://user-images.githubusercontent.com/49032117/175838442-1eab2524-1b7b-4283-a9df-41d171682882.png)

**Comment by BensDream** [comment]
That would be a big help, for sure!

**Comment by aymericingargiola** [comment]
@BensDream you can download last release and play with the 2 new conditions :
![image](https://user-images.githubusercontent.com/49032117/176306450-a1fbcbf1-61e2-4b8b-92bf-125bf3c46a5a.png)

The conditions will also apply based on the filters you select (for exemple : Character: Isaac, Save: 2, Search input: SEED)

Let me know if it's good for you

**Comment by BensDream** [comment]
@aymericingargiola This looks super useful, thank you so much! I imagine until the final boss feature is implemented, final boss is stored in the seed, right?

**Comment by aymericingargiola** [comment]
@BensDream Yes but even if it not the case i can guess it from the final floor :)

**Comment by aymericingargiola** [comment]
@BensDream Sorry for the time, i'v just added in last release main bosses card to runs but maybe you also need a filter ?
https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.3

**Comment by BensDream** [comment]
This seems super useful, thank you! Will the change in DB erase my past runs or will they be converted?

**Comment by aymericingargiola** [comment]
You will keep all your previous runs :)
