### ISSUE TITLE
Don't have a search bar

### ISSUE THREAD

**Issue by Shaniquaniminiquani** [aymericingargiola/repentance-run-tracker#35]
Odd timing to have come back to repentance and see you update the tracker live lmao but I seem to no longer have the ability to filter through my past runs? I seem to remember having a search bar before at least where I could search by character, date etc, was wondering if this isn't a supported feature anymore.
<img width="725" alt="ExAMPLE" src="https://user-images.githubusercontent.com/109847642/180596641-8bbbef6f-3952-4b1e-8d14-cd8e62b5ccb0.png">
I've never used github before so I'm not sure if I wrote this in the correct place. The background of the application seems to have changed also (I think*) used to be slightly darker iirc, would love some kind of dark mode

**Comment by aymericingargiola** [comment]
@Shaniquaniminiquani That's strange ! Can you give me your last backup ?
Close the app and go to : C:\Users\YOURNAME\AppData\Roaming\repentanceruntracker\backups -> give me the last created zip

I was thinking about a dark mode hehe, i have to think about that yes

**Comment by Shaniquaniminiquani** [comment]
[backup_datas_07-23-22-042317AM.zip](https://github.com/aymericingargiola/repentance-run-tracker/files/9173372/backup_datas_07-23-22-042317AM.zip)
Here it is

**Comment by aymericingargiola** [comment]
@Shaniquaniminiquani I found the issue, looks like you have a corrupted run :

![image](https://user-images.githubusercontent.com/49032117/180597259-74bba95a-cf09-4e2f-9570-19d26dcabce9.png)

I fixed the filters but i'm checking if i can automatically remove corrupted runs

**Comment by Shaniquaniminiquani** [comment]
Ah yeah, I seem to remember that happening when I tried launching the tracker with mods on way back. It would just instantly crash and give me corrupted runs. Most went away but I remember not being able to get rid of one. Thankfully I don't usually play with mods, my streak had died the run before that so I was peer pressured into playing with mods 💀🙏

**Comment by aymericingargiola** [comment]
It should be fixed in last release let me know !
https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.4

**Comment by Shaniquaniminiquani** [comment]
![image](https://user-images.githubusercontent.com/109847642/180599874-776bca9d-b1a1-47cc-91f8-4a5cd7169e8c.png)
Does indeed seem to be fixed. Ty 🙏
