### ISSUE TITLE
Have runs be backedup on run completion instead of on application close

### ISSUE THREAD

**Issue by Shaniquaniminiquani** [aymericingargiola/repentance-run-tracker#37]
Had a poweroutage yesterday and when I opened the run tracker today I was reverted to what I assume is the last backup from the 25th losing around 20 runs. Don't think I can recover the lost runs but would appreciate not losing any more going forward by having runs be backed up when they're completed instead of waiting for the app to close 🙏

**Comment by aymericingargiola** [comment]
Oh sorry to hear that !

I'll work on this no issue, more backups improvement !

**Comment by aymericingargiola** [comment]
Should be fixed from 0.7.7 release ! https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.7
