### ISSUE TITLE
Show streak count on death & Adjusted streak optimization

### ISSUE THREAD

**Issue by Shaniquaniminiquani** [aymericingargiola/repentance-run-tracker#42]
As the title suggests, would be a good quality of life change for deaths to show what your current streak was prior to them, when sorting by loses you would be able to gain a lot more information this way. Ideally this number would be going off of the adjusted streak number which would also fix the "best win streak" option not showing the actual best winstreak 🙏

**Comment by aymericingargiola** [comment]
Thanks, i'll need to rework how i do the winstreaks and archive lost streaks !

**Comment by aymericingargiola** [comment]
It should now works for futur and current winstreak from last update ! : https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.10

But unfortunately not for older winstreaks

**Comment by Shaniquaniminiquani** [comment]
Ah I won't be able to check if it works in a while if it's doesn't work retroactively but I might try some lost streaking to make sure 👍👍
