### ISSUE TITLE
[Question] Does this work with the Steam Deck?

### ISSUE THREAD

**Issue by BensDream** [aymericingargiola/repentance-run-tracker#49]
I'm due to receive mine next week, would hate to have to install Windows on it but if it doesn't work on Proton I might have to!

**Comment by BensDream** [comment]
After having received it, the answer seems to be no :( 

Neither Lutris or Wine want to work, so looks like I'm selling it!

**Comment by aymericingargiola** [comment]
No the tracker don't work on native linux, i tried but it dosen't compile and there are no errors to give me ideas about why...

If you launch it from proton it could works but it will never reach the game folders because all proton apps are sandboxed

**Comment by aymericingargiola** [comment]
There is now a linux build, can you try it ? https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.14

Read the wiki page also : https://github.com/aymericingargiola/repentance-run-tracker/wiki/Steam-Deck-support-(Linux)
