### ISSUE TITLE
Tracker doesn't work on Linux or Steam Deck

### ISSUE THREAD

**Issue by xEden95x** [aymericingargiola/repentance-run-tracker#50]
**Describe the bug**
The tracker opens using Proton, but it doesn't notice the game is running - I would imagine it's because it's trying to call tasklist in methods.js, which isn't implemented in Proton/Wine.

It also doesn't install itself to the game's mod folder - I've put the right location, but no files get deposited in there.

**Screenshots**
N/A

**Error zip file**
N/A

**Additional context**
N/A

**Comment by aymericingargiola** [comment]
The tracker dosen't support linux (i tried to compile but it fails and there is no errors...) and if you launch it via proton it will never reach the game folder since all proton apps are sandboxed

**Comment by xEden95x** [comment]
@aymericingargiola If it helps at all, I'm also running the game through Proton (otherwise I can't access the latest DLC). There seems to be a way to get them to run "together" (as in, not sandboxed) from one another using ProtonTricks, but the reliance on tasklist is still there.

Is there any way of working around this to get it functioning? It's genuinely the one thing stopping me from keeping my Deck!

**Comment by aymericingargiola** [comment]
I'm not sure, it's very hard to debug this and there is still a possibility to install windows on the steam deck if it's very important. The best way to do it is to port my app to native linux and manually link the game folders (log.txt location and mods folder), but the app dosen't even start/compile on linux without any error code

**Comment by aymericingargiola** [comment]
Linux build added with wiki page : https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.14
