### ISSUE TITLE
Ability to choose what save files are tracked

### ISSUE THREAD

**Issue by Shaniquaniminiquani** [aymericingargiola/repentance-run-tracker#52]
Might sound like a weird suggestion but one of my save files is exclusively for speedrunning/ trying out item combos and whenever I do runs with it I either need to close the app or delete the run on the tracker manually (Usually do the latter). Normally Its just an inconvenience i deal with but I accidentally deleted the run I lost on in my streak so I thought I'd suggest it

Additionally allowing filtering by save file might be good implementation.

Ps. Is there anyway to manually add a run into the tracker in/ recover a run? Would be cool if the last idk 3 deleted runs where still saved in the background in case of accidental deletion 💀
![image](https://user-images.githubusercontent.com/109847642/204818824-baa2ad91-0a0f-4c9e-a353-07daa6915011.png)

**Comment by aymericingargiola** [comment]
> I accidentally deleted the run I lost on in my streak
> Ps. Is there anyway to manually add a run into the tracker in/ recover a run? Would be cool if the last idk 3 deleted runs where still saved in the background in case of accidental deletion

Wasn't you able to recover it from the trash bin icon at the top right ? 
![image](https://user-images.githubusercontent.com/49032117/204823942-495726fc-ebac-4100-acb2-341af66deec6.png)


> Additionally allowing filtering by save file might be good implementation

You don't talk about this ? I'm a bit loss ahah
![image](https://user-images.githubusercontent.com/49032117/204823673-be46aad6-b68f-4c8c-88cd-ac797a53b56d.png)

**Comment by Shaniquaniminiquani** [comment]
Ahh, I don't have that filter 
![image](https://user-images.githubusercontent.com/109847642/204825612-41326cb7-6ac6-475f-9612-09fb279b2c2e.png)

and I was always scared of clicking the trash can haha, I thought that would wipe all my runs for some reason ty for that haha. But yeah, I think a save file listener would still help out, I never really need to track my third save file

**Comment by aymericingargiola** [comment]
> Ahh, I don't have that filter

Whaaat ? That means you have something corrupted in your json or you only have runs within one save ! Can you send me your runs.json ?

> But yeah, I think a save file listener would still help out, I never really need to track my third save file

You mean an option where you can select the saves that you don't want to record the runs in the app ? I can do that !

**Comment by aymericingargiola** [comment]
> Yes that's what I meant

Ok then i'll do it !

> When you get a modded item does the tracker not display it or does it crash

I don't support mods, but Fiend Folio is supported ! i didn't tried other mods but it should'nt make the app crash, it should show an unknow thing or miss match if the id is the same as one of the Repentance ids (items, monsters...)

**Comment by aymericingargiola** [comment]
It is now released let me know if it's good for you then i close the ticket !

![image](https://user-images.githubusercontent.com/49032117/205287566-5d98b300-5e7a-4e38-9497-29a17cf7ac1a.png)

**Comment by Shaniquaniminiquani** [comment]
I believe it's working! Thanks a lot 🙏

By the way are challenges bugged with the tracker currently? I noticed all 4 of the challenges I did last night resulted in broken runs 
![image](https://user-images.githubusercontent.com/109847642/205415058-505f5526-1bf6-45ff-8d29-7c6d3148b027.png)
It's not really an issue since I will really only do them once (Hence why I hadn't noticed until now even), but thought I'd mention it 

also there's a weird graphical thing that happens to the active item and character graphics when you drag the run items list past the maximum/minimum amount which becomes more pronounced the less floors there are (It's hard to explain so I just recorded a small clip of it)

https://user-images.githubusercontent.com/109847642/205415539-c78955c0-12df-4b1b-97fb-9096cef0320b.mp4

Lastly I also came up with another suggestion while streaming last night: It would be cool if to the right of your current win streak on the app it would show your best win streak number to compare. 
![image](https://user-images.githubusercontent.com/109847642/205415900-9f5aca63-6ca6-4f17-a7a0-b7155e5254a9.png)

The extra mile would be if this also aligned to the specific win condition you have set (Ie, say my highest winstreak ever was like idk 60, but my highest winstreak with the condition to lamb only was 20, it would show me 20 because it's what I have the winstreak save set to).

**Comment by aymericingargiola** [comment]
> By the way are challenges bugged with the tracker currently? I noticed all 4 of the challenges I did last night resulted in broken runs

Yeah i actually don't support challenges/specific seeds, not on the scope, but i can give a look, i think i miss informations from the logs unfortunately...

> also there's a weird graphical thing that happens to the active item and character graphics when you drag the run items list past the maximum/minimum amount which becomes more pronounced the less floors there are (It's hard to explain so I just recorded a small clip of it)

It's not a glitch, it's the way the carousel library works actually 😅 (swiper)

> Lastly I also came up with another suggestion while streaming last night: It would be cool if to the right of your current win streak on the app it would show your best win streak number to compare.

I can check that yes, would you mine to do an other ticket for this feature request so i can close this one ?

If i understand well, we will check specific save AND specific characters list + boss list to compare if a previous winstreak exist with exact same rules and take the one with highest wins to show next to the current winstreaks

**Comment by Shaniquaniminiquani** [comment]
Ah yeah don't worry about the challenges/visual bug they aren't really intrusive was just making sure they were documented haha

>If i understand well, we will check specific save AND specific characters list + boss list to compare if a previous winstreak exist with exact same rules and take the one with highest wins to show next to the current winstreaks

Yes this is what I mean. Will create a new request 🙏
