### ISSUE TITLE
Pre-emptively requesting support for the new update!

### ISSUE THREAD

**Issue by ER-95** [aymericingargiola/repentance-run-tracker#63]
Forgive my paranoia, but this is my ONLY mandatory Isaac plugin and I'm terrified that it won't get support when the new update launches in the coming days...

Would it be possible to confirm if this will or won't receive updates for the upcoming patch please?

Many thanks

**Comment by aymericingargiola** [comment]
Yes i'll check ! but i'm not sure what can or will be broken, maybe everything will be fine

**Comment by aymericingargiola** [comment]
Apparently every mods are broken for now so you will not have any extra informations i add with my mod (hearts, stats....)

**Comment by aymericingargiola** [comment]
I'v made an update to support Repentance+ : https://github.com/aymericingargiola/repentance-run-tracker/releases/latest

But the mod (and lots of other mods) dosen't work for now, so no extra informations like health or character stats

**Comment by ER-95** [comment]
> I'v made an update to support Repentance+ : https://github.com/aymericingargiola/repentance-run-tracker/releases/latest
> 
> But the mod (and lots of other mods) dosen't work for now, so no extra informations like health, map, or character stats etc...

Thank you! Do you know roughly when this will be fully functional for Repentance+ in single player mode?

I won't be playing co-op, but being able to thoroughly track my single player runs would be incredible.

**Comment by aymericingargiola** [comment]
This is for single player!

**Comment by aymericingargiola** [comment]
This is for solo only! It doesn't really work for online since too many things can happen and logs are not very useful to maintain tracking during online runs.

You can already use it

**Comment by ER-95** [comment]
Sorry, slightly confused - you said in your last post "no extra informations like health, map, or character stats" - does this mean there are further updates to come before it's fully functional with solo play in Repentance+? Or is the functionality now the same as it was before the update?

**Comment by aymericingargiola** [comment]
The extra informations are from the mod "Repentance Run Tracker Extended", but no mods are working on repentance+ so it will track your runs but without extra informations, I don't know if you play with the mod or not.

But for now I can't do anything more, it will be on repentance team to make mods working again

**Comment by ER-95** [comment]
I was under the impression that you could manually move mods into your Repentance+ mods folder - would the mod be able to pull the information if I manually move it like the devs say I should?

**Comment by aymericingargiola** [comment]
I already did it, and the mod will install automatically here if you check repentance+ support in the options but it doesn't work unfortunately, debug string api doesn't write in the log file for now

**Comment by ER-95** [comment]
Ah, I see - so the mod is potentially not going to fully function ever again unless the Repentance devs make changes?

**Comment by aymericingargiola** [comment]
Exactly!

**Comment by Shaniquaniminiquani** [comment]
> the mod will install automatically here if you check repentance+ support in the options

ah is that what that did? I thought that was just to make the app work in rep+ 😭. Might be worth rewording the option for clarity if they ever fix the mod’s api. Something like “Repentance+ Extended Tracker Mod support” 

Just to clarify, would unchecking the option completely uninstall the mod or just “disable” it? I’ve only been doing coop runs so haven’t gotten a chance to test haha. The new wiki hrefs are working though 👍

**Comment by aymericingargiola** [comment]
If you uncheck it will rollback to old repentance folders yes (after restart) 🙂

**Comment by ER-95** [comment]
@aymericingargiola It seems that today's patch "fixed several issues in the modding API" - would you be able to confirm if this fixes the issue with Repentance Run Tracker Extended please? Thank you!!

**Comment by aymericingargiola** [comment]
> @aymericingargiola It seems that today's patch "fixed several issues in the modding API" - would you be able to confirm if this fixes the issue with Repentance Run Tracker Extended please? Thank you!!

It does work indeed ! But the health is bugged
![image](https://github.com/user-attachments/assets/02fd00ad-1d4d-411b-b5aa-92e4e4ec4593)

**Comment by ER-95** [comment]
@aymericingargiola Woo, thank you for confirming! Is the health something that should be fixable?

**Comment by aymericingargiola** [comment]
> @aymericingargiola Woo, thank you for confirming! Is the health something that should be fixable?


I don't know yet, my code didn't changed so i assume the API isn't fully functionnal yet

**Comment by aymericingargiola** [comment]
@ER-95 My bad, it does work in fact, everything is good from what i see

![image](https://github.com/user-attachments/assets/34317335-5b6b-4adc-8458-92c310306dac)

**Comment by ER-95** [comment]
@aymericingargiola I can't seem to get the in-game mod to actually install, despite pasting the mods directory into the settings - is there anything I need to do beyond that, or should it just be added automatically?

**Comment by aymericingargiola** [comment]
> @aymericingargiola I can't seem to get the in-game mod to actually install, despite pasting the mods directory into the settings - is there anything I need to do beyond that, or should it just be added automatically?

They revert the mod folder to the default one so if you had it before it should still be here, also don't forget to check the option so the app should read the right logs (repentance+ folder)

Or maybe retry to uncheck the option, relaunch the app, check and relaunch the app again

**Comment by aymericingargiola** [comment]
I will have to update the app again anyway, since they revert the mod folder "Documents\My Games\Binding of Isaac Repentance+\mods" to "Steam\steamapps\common\The Binding of Isaac Rebirth\mods"
