### ISSUE TITLE
Games aren't being recorded

### ISSUE THREAD

**Issue by Shaniquaniminiquani** [aymericingargiola/repentance-run-tracker#64]
I haven't had a chance to run the tracker since rep+ since I'm working on a coop only dead god save currently but I was forced to play a run on my streak file today and the run tracker didn't seem to record it even though visually it said it was "watching the game" at the top. 

<img width="507" alt="Screenshot_8474" src="https://github.com/user-attachments/assets/e03e7d5a-f801-4961-b8b4-8fa6fe2bb1e1" />

Ignore the fact that it doesn't display a winstreak rule at the top, they became bugged for me a long time ago (probably over a year now) but its only visually bugged and was still usable on the filters etc and I know you'd been pretty busy so I never brought it up. I think I've encountered a couple of other bugs as well but nothing that should be affecting the games from recording.

I made a backup of my save and restarted a couple runs to make sure it was consistent and not a one time off thing and it doesn't seem to be working at all.

This is my options to show save 1 isn't being ignored:
![image](https://github.com/user-attachments/assets/2fe66596-729e-437c-8731-e8d08a02a3be)

Rep+ is currently really unstable so I'm delaying streaking on it until I finish my third save file at minimum which I'm only about half way done with so no real rush if you can get to it, but if you can help me get it working again (recording runs) for when I do need it,  I would appreciate it.

This is a copy of my latest backup:
[backup_datas_12-22-24-025046PM.zip](https://github.com/user-attachments/files/18223074/backup_datas_12-22-24-025046PM.zip)

Let me know if you need anything else, again feel free to take as long as you need, no rush! Enjoy your holidays 🎅

**Comment by aymericingargiola** [comment]
I'll try to take a look at it, by any chance did you have enabled in the settings repentance+ suport ? 

If the game is watched but nothing happens it is because it's either reading the wrong log file (classic repentance) or the repentance+ folder has mooved

**Comment by Shaniquaniminiquani** [comment]
>by any chance did you have enabled in the settings repentance+ support ?

I didn't have it checked when I tried today but I did enable it briefly when rep+ came out before you [informed](https://github.com/aymericingargiola/repentance-run-tracker/issues/63#issuecomment-2489149272) me that “rep+ support” was just to download the Issac run tracker extended mod to the relevant directory natively within the tracker. 

I dont use mods so I figured unchecking it wouldn’t cause an issue haha, does it need to have the mod running for the tracker to work now? Or did we misunderstand each other before and “rep+” support is not mod related at all

**Comment by aymericingargiola** [comment]
You need to check the option because it's not only for mod but also for logs, logs folder is different 🙂 mod is not required

**Comment by Shaniquaniminiquani** [comment]
Ahhh that makes a lot more sense, I thought it would automatically latch onto whatever version the game was running. I'll try it with the rep+ support enabled and see if it works

**Comment by Shaniquaniminiquani** [comment]
> I'll try it with the rep+ support enabled and see if it works

Yeah it seems to work fine now 😭, sorry for the confusion haha
